package factory.unidades;

public enum TipoUnidad {
	TERRAN_MARINE,TERRAN_GOLLIAT,TERRAN_ESPECTRO,TERRAN_NAVE_CIENCIA,TERRAN_NAVE_TRANSPORTE,
	PROTOSS_ZEALOT,PROTOSS_DRAGON,PROTOSS_SCOUT,PROTOSS_ALTO_TEMPLARIO,PROTOSS_NAVE_TRANSPORTE,
	ERROR

}
