package factory.construcciones;

public enum TipoEdificio {
	TERRAN_CENTRO_MINERAL, TERRAN_REFINERIA, TERRAN_DEPOSITO_SUMINISTROS, TERRAN_BARRACA, TERRAN_FABRICA, TERRAN_PUERTO_ESTELAR, 
	PROTOSS_NEXO_MINERAL, PROTOSS_ASIMILADOR, PROTOSS_PILON, PROTOSS_ACCESO, PROTOSS_PUERTO_ESTELAR, PROTOSS_ARCHIVO_TEMPLARIO, BASE_RECURSOS
}
